# Copyright 2022 The OWASP Coraza contributors
# SPDX-License-Identifier: Apache-2.0

FROM curlimages/curl
USER root

WORKDIR /workspace

RUN apk add --no-cache bash

COPY ./e2e/e2e-example.sh /workspace/e2e-example.sh
RUN cat /workspace/e2e-example.sh

ENV ENVOY_HOST=caddy:8080
ENV HTTPBIN_HOST=httpbin:8081

CMD ["bash","-c", "/workspace/e2e-example.sh"]