name: Tests

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "LICENSE"

permissions: {}

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.25.x, 1.26.x]
        os: [ubuntu-latest]
        xcaddy-version: [v0.4.5]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          lfs: true
          fetch-depth: 0 #for better blame info

      - name: Tests and coverage
        run: go run mage.go coverage

      - name: Install xcaddy
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@${{ matrix.xcaddy-version }}

      - name: Build caddy
        run: go run mage.go buildCaddyLinux

      - name: Run e2e tests
        run: go run mage.go e2e

      - name: Run regression tests (ftw)
        run: go run mage.go ftw

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        if: success() || failure()
        with:
          name: ftw-caddy-logs-${{ matrix.go-version }}
          path: build/ftw-caddy.log
